{
    "tracks": {
        "href": "https://api.spotify.com/v1/search?query=You+are+my+sunshine&type=track&offset=0&limit=1",
            "items": [
                {
                    "album": {
                        "album_type": "single",
                        "artists": [
                            {
                                "external_urls": {
                                    "spotify": "https://open.spotify.com/artist/2TL8gYTNgD6nXkyuUdDrMg"
                                },
                                "href": "https://api.spotify.com/v1/artists/2TL8gYTNgD6nXkyuUdDrMg",
                                "id": "2TL8gYTNgD6nXkyuUdDrMg",
                                "name": "Jasmine Thompson",
                                "type": "artist",
                                "uri": "spotify:artist:2TL8gYTNgD6nXkyuUdDrMg"
                            }
                        ],
                        "available_markets": [
                            "AD",
                            "AR",
                            "AT",
                            "AU",
                            "BE",
                            "BG",
                            "BO",
                            "BR",
                            "CA",
                            "CH",
                            "CL",
                            "CO",
                            "CR",
                            "CY",
                            "CZ",
                            "DE",
                            "DK",
                            "DO",
                            "EC",
                            "EE",
                            "ES",
                            "FI",
                            "FR",
                            "GB",
                            "GR",
                            "GT",
                            "HK",
                            "HN",
                            "HU",
                            "ID",
                            "IE",
                            "IL",
                            "IS",
                            "IT",
                            "JP",
                            "LI",
                            "LT",
                            "LU",
                            "LV",
                            "MC",
                            "MT",
                            "MX",
                            "MY",
                            "NI",
                            "NL",
                            "NO",
                            "NZ",
                            "PA",
                            "PE",
                            "PH",
                            "PL",
                            "PT",
                            "PY",
                            "RO",
                            "SE",
                            "SG",
                            "SK",
                            "SV",
                            "TH",
                            "TR",
                            "TW",
                            "US",
                            "UY",
                            "VN",
                            "ZA"
                        ],
                        "external_urls": {
                            "spotify": "https://open.spotify.com/album/5ueNN8xbGK6BMFnLjeiXUM"
                        },
                        "href": "https://api.spotify.com/v1/albums/5ueNN8xbGK6BMFnLjeiXUM",
                        "id": "5ueNN8xbGK6BMFnLjeiXUM",
                        "images": [
                            {
                                "height": 640,
                                "url": "https://i.scdn.co/image/ac32211629fa6e0bab6703f12a8331294d4adba3",
                                "width": 640
                            },
                            {
                                "height": 300,
                                "url": "https://i.scdn.co/image/e42145afec4425afb709b4cc50396f07cfbf895f",
                                "width": 300
                            },
                            {
                                "height": 64,
                                "url": "https://i.scdn.co/image/50f63c00be924846dbceea3af8ab24effee8e025",
                                "width": 64
                            }
                        ],
                        "name": "You Are My Sunshine",
                        "release_date": "2016-12-09",
                        "release_date_precision": "day",
                        "type": "album",
                        "uri": "spotify:album:5ueNN8xbGK6BMFnLjeiXUM"
                    },
                    "artists": [
                        {
                            "external_urls": {
                                "spotify": "https://open.spotify.com/artist/2TL8gYTNgD6nXkyuUdDrMg"
                            },
                            "href": "https://api.spotify.com/v1/artists/2TL8gYTNgD6nXkyuUdDrMg",
                            "id": "2TL8gYTNgD6nXkyuUdDrMg",
                            "name": "Jasmine Thompson",
                            "type": "artist",
                            "uri": "spotify:artist:2TL8gYTNgD6nXkyuUdDrMg"
                        }
                    ],
                    "available_markets": [
                        "AD",
                        "AR",
                        "AT",
                        "AU",
                        "BE",
                        "BG",
                        "BO",
                        "BR",
                        "CA",
                        "CH",
                        "CL",
                        "CO",
                        "CR",
                        "CY",
                        "CZ",
                        "DE",
                        "DK",
                        "DO",
                        "EC",
                        "EE",
                        "ES",
                        "FI",
                        "FR",
                        "GB",
                        "GR",
                        "GT",
                        "HK",
                        "HN",
                        "HU",
                        "ID",
                        "IE",
                        "IL",
                        "IS",
                        "IT",
                        "JP",
                        "LI",
                        "LT",
                        "LU",
                        "LV",
                        "MC",
                        "MT",
                        "MX",
                        "MY",
                        "NI",
                        "NL",
                        "NO",
                        "NZ",
                        "PA",
                        "PE",
                        "PH",
                        "PL",
                        "PT",
                        "PY",
                        "RO",
                        "SE",
                        "SG",
                        "SK",
                        "SV",
                        "TH",
                        "TR",
                        "TW",
                        "US",
                        "UY",
                        "VN",
                        "ZA"
                    ],
                    "disc_number": 1,
                    "duration_ms": 157868,
                    "explicit": false,
                    "external_ids": {
                        "isrc": "USAT21603480"
                    },
                    "external_urls": {
                        "spotify": "https://open.spotify.com/track/5qMjtrGnezsafpH4oqg7oU"
                    },
                    "href": "https://api.spotify.com/v1/tracks/5qMjtrGnezsafpH4oqg7oU",
                    "id": "5qMjtrGnezsafpH4oqg7oU",
                    "is_local": false,
                    "name": "You Are My Sunshine",
                    "popularity": 65,
                    "preview_url": "https://p.scdn.co/mp3-preview/754526e8d2eaa7d691b999772309e378991d77db?cid=356cadd4430f4c88b3898be7345e5867",
                    "track_number": 1,
                    "type": "track",
                    "uri": "spotify:track:5qMjtrGnezsafpH4oqg7oU"
                }
            ],
                "limit": 1,
                    "next": "https://api.spotify.com/v1/search?query=You+are+my+sunshine&type=track&offset=1&limit=1",
                        "offset": 0,
                            "previous": null,
                                "total": 11308
    }
}


